reset;

model EQ10_Projet_Test.mod;
data EQ10_Projet_Test.dat;
option solver gurobi;
#option gurobi_options "outlev 1";
solve;
expand > EQ10_Projet_Test.txt;
display u;
display assignation;
display nb_etudiant_dans_bus;
display utilise_bus;
display deplacement;
display temps;
display {i in L, j in L, b in B: i != j} d[i, j] * deplacement[i, j, b];
display sum {i in L, j in L, b in B: i != j} d[i, j] * deplacement[i, j, b];
display {b in B} sum {i in L, j in L : i != 0} temps[i,j,b];
display {b in B} sum {i in L, j in L} temps[i,j,b];